name: CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Code style check (Spotless)
        run: ./gradlew spotlessCheck
        shell: bash  # Ensures compatibility on Windows
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
        shell: bash
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests (${{ matrix.os }})
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
